Repository WildCodeSchool/lyon-js-0320-p2-g1, pull requests merged in 2020-05, with the labels that each got.

#30 Feature/us9
  package-lock.json
  package.json
  src/App.js
  src/components/all-cocktails/AllCocktails.css
  src/components/all-cocktails/AllCocktails.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/guestbook/Animation.css
  src/components/guestbook/GuestBook.css
  src/components/guestbook/GuestBook.js
  src/components/home/CompoCocktail.js
  src/components/home/Home.css
  src/components/home/Home.js~dev
  src/components/home/Quizz.js
  src/images/allcocktail1.jpg
  src/images/allcocktail2.jpg
Labels: Corrections done

#36 Feature/us15
  src/components/footer/Footer.css
  src/components/footer/Footer.js
Labels: Reviewed

#34 Feature/us10
  src/components/all-cocktails/AllCocktails.css
  src/components/all-cocktails/AllCocktails.js
  src/components/footer/Footer.css
  src/components/footer/Footer.js
  src/components/home/CompoCocktail.js
  src/components/navbar/Navbar.js
  src/images/allcocktail1.jpg
  src/images/allcocktail2.jpg
  src/images/allcocktails.jpg
  src/images/subTitleImg.png
Labels: Corrections done

#39 Feature/us17
  package-lock.json
  package.json
  public/index.html
  src/components/all-cocktails/AllCocktails.css
  src/components/all-cocktails/AllCocktails.js
  src/components/home/CompoCocktail.js
  src/components/home/Home.css
  src/components/home/Home.js
  src/components/home/Home.js~dev
  src/components/home/Quizz.js
  src/components/navbar/Navbar.css
Labels: Reviewed

#41 Feature/us17
  src/components/all-cocktails/AllCocktails.css
  src/components/all-cocktails/AllCocktails.js
  src/components/home/CompoCocktail.js
  src/components/home/Home.css
  src/components/home/Home.js
  src/components/navbar/Navbar.css
Labels: Reviewed

#42 add quizz
  src/App.js
  src/components/footer/Footer.css
  src/components/guestbook/GuestBook.js
  src/components/home/CompoCocktail.js
  src/components/home/Home.css
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.js
  src/components/quizz/Quizz.css
  src/components/quizz/Quizz.js
  src/data/questions.js
  src/images/logo-cocktail.png
  src/images/quizz.jpg
Labels: Changes requested
